# Generated by Django 5.0.7 on 2024-10-27 06:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=255
            ),
            preserve_default=False,
        ),
    ]
